### 初期画面

GET http://localhost:3000

### ユーザ全取得

GET http://localhost:3000/users

### ユーザ一部取得

GET http://localhost:3000/users/1

### ユーザ追加

POST http://localhost:3000/users
Content-Type: application/json
Accept: application/json

{
  "name": "sample2",
  "birthday": "1999-07-02",
  "password": "yuuhan"
}

### 支払い全取得

GET http://localhost:3000/payments

### 支払い一部取得

GET http://localhost:3000/payments/1

### 支払い追加

POST http://localhost:3000/payments
Content-Type: application/json
Accept: application/json

{
  "name": "meeting3",
  "payerId": 1,
  "payerCost": 4000
}

### 支払い済みに変更

PATCH  http://localhost:3000/payments/3
Content-Type: application/json
Accept: application/json

{
  "isSettled": true
}


